config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :teams, only: [:index, :show, :new, :create] do
    resources :players, only: :create
  end

  resources :players, only: :show

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players # def players Player.where(team_id: self.id) end

  def players_whort_more_than(value)
    self.players.where("players.value >= ?", value) # 1000; DROP table players;
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def create
    @team = Team.find(params[:team_id])
    @player = Player.new(player_params)
    @player.team = @team
    if @player.save
      redirect_to team_path(@team)
    else
      # render 'team_path'
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  private

  def player_params
    params.require(:player).permit(:name, :position, :value, :photo_url)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @players_1M = @team.players_whort_more_than(1000000)
    @player = Player.new
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to team_path(@team)
    else
      render :new
    end
  end

  private

  def team_params
    params.require(:team).permit(:name, :city, :number_fans)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamsManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render 'shared/sidebar' %>
    <%= render 'shared/bottom_navbar' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>

app/views/shared/_bottom_navbar.html.erb
<nav id="bottom-nav">
  <div class="container">
    <ul id="bottom-list" class="flex-container">
      <li class="<%= if yield(:menu) == 'teams' then ' active' end %>">
        <%= link_to teams_path do %>
          <figure>
            <i class="fas fa-users"></i>
            <figcaption>Teams</figcaption>
          </figure>
        <% end %>
      </li>
      <li class="<%= if yield(:menu) == 'about' then ' active' end %>">
        <%= link_to root_path do %>
          <figure>
            <i class="far fa-building"></i>
            <figcaption>About Us</figcaption>
          </figure>
        <% end %>
      </li>
      <li class="<%= if yield(:menu) == 'profile' then ' active' end %>">
        <%= link_to root_path do %>
          <figure>
            <i class="fas fa-user"></i>
            <figcaption>Profile</figcaption>
          </figure>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <i id="sidebar-icon" class="fas fa-bars d-block d-sm-none"></i>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div id="sidebar">
  <div><%= link_to t(:home), root_path %></div>
  <hr>
  <% if user_signed_in? %>
    <div>
      <%= link_to t(:logout), destroy_user_session_path, method: :delete %>
    </div>
  <% else %>
    <div>
      <%= link_to t(:login), new_user_session_path %>
    </div>
  <% end %>
</div>